name: effect_types
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0-0.0.dev <4.0.0'


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  freezed: ^2.3.2
  build_runner: ^2.4.1

dependencies:
  checks: ^0.2.1
  collection: ^1.17.1
  fast_immutable_collections: ^9.0.0
  freezed_annotation: ^2.2.0
